# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: 将站点部署到Github Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 从git中取出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      # - uses: pnpm/action-setup@v3 # 如果使用 pnpm，请取消注释
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: 设置node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # 或 pnpm / yarn
      - name: 设置界面
        uses: actions/configure-pages@v4
      - name: 安装依赖项
        run: npm ci # 或 pnpm install / yarn install / bun install
      - name: 使用VitePress框架构建
        run: npm run docs:build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
      - name: 查看路径
        run: pwd
      - name: 查看当前路径文件
        run: ls
      - name: cd 
        run: cd docs
      - name: ls
        run: ls
      - name: 上传编译后的界面
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到GithubPages
        id: deployment
        uses: actions/deploy-pages@v4
#远程服务器
  deploy_remote_server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署文件到远程服务器
        uses: c0c1/scp-action@v1.0
        with:
            src: /home/runner/work/blog/blog/docs/.vitepress/dist/*
            host: 112.249.183.60
            remote: /root
            port: 7767
            user: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}


     
